// <auto-generated />
using System;
using Gvn.GvnAI.Dictionary.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gvn.GvnAI.Dictionary.Infrastructure.Migrations
{
    [DbContext(typeof(DictionaryDbContext))]
    [Migration("20260404064914_AddUserIdToWords")]
    partial class AddUserIdToWords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.Etymology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OriginLanguageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OriginLanguageId");

                    b.HasIndex("WordId");

                    b.ToTable("etymologies", (string)null);
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.Example", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("TargetText")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("TranslationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SenseId");

                    b.HasIndex("TranslationId");

                    b.ToTable("examples", (string)null);
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.Favorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WordId");

                    b.HasIndex("UserId", "WordId")
                        .IsUnique();

                    b.ToTable("favorites", (string)null);
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.PartOfSpeech", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("parts_of_speech", (string)null);
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.Pronunciation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IpaTranscription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsStandard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Variant")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WordId");

                    b.ToTable("pronunciations", (string)null);
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.QuizAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CorrectTranslationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuizSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SelectedTranslationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuizSessionId");

                    b.HasIndex("WordId");

                    b.ToTable("quiz_answers", (string)null);
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.QuizSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("WrongCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("quiz_sessions", (string)null);
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.Register", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("registers", (string)null);
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.Sense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DefinitionShort")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DifficultyLevel")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<Guid?>("DomainId")
                        .HasColumnType("uuid");

                    b.Property<int?>("FrequencyRank")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RegisterId")
                        .HasColumnType("uuid");

                    b.Property<int>("SenseNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.HasIndex("RegisterId");

                    b.HasIndex("WordId", "SenseNumber")
                        .IsUnique();

                    b.ToTable("senses", (string)null);
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.SenseAntonym", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenseId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenseId2")
                        .HasColumnType("uuid");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("SenseId2");

                    b.HasIndex("SenseId1", "SenseId2")
                        .IsUnique();

                    b.ToTable("sense_antonyms", (string)null);
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.SenseSynonym", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenseId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenseId2")
                        .HasColumnType("uuid");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("SenseId2");

                    b.HasIndex("SenseId1", "SenseId2")
                        .IsUnique();

                    b.ToTable("sense_synonyms", (string)null);
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.SubjectDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("domains", (string)null);
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.Translation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<string>("EquivalenceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("PartOfSpeechId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RegisterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetLanguageId")
                        .HasColumnType("uuid");

                    b.Property<string>("TranslationText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("PartOfSpeechId");

                    b.HasIndex("RegisterId");

                    b.HasIndex("TargetLanguageId");

                    b.HasIndex("SenseId", "TargetLanguageId");

                    b.ToTable("translations", (string)null);
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DifficultyLevel")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int?>("FrequencyRank")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompound")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsIdiom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsProperNoun")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Lemma")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PartOfSpeechId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PartOfSpeechId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("Lemma", "LanguageId", "UserId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("words", (string)null);
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.WordRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceWordId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetWordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("TargetWordId");

                    b.HasIndex("SourceWordId", "TargetWordId", "Type")
                        .IsUnique();

                    b.ToTable("word_relationships", (string)null);
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.Etymology", b =>
                {
                    b.HasOne("Gvn.GvnAI.Dictionary.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("OriginLanguageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Gvn.GvnAI.Dictionary.Domain.Entities.Word", null)
                        .WithMany("Etymologies")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.Example", b =>
                {
                    b.HasOne("Gvn.GvnAI.Dictionary.Domain.Entities.Sense", null)
                        .WithMany("Examples")
                        .HasForeignKey("SenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gvn.GvnAI.Dictionary.Domain.Entities.Translation", null)
                        .WithMany()
                        .HasForeignKey("TranslationId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.Favorite", b =>
                {
                    b.HasOne("Gvn.GvnAI.Dictionary.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gvn.GvnAI.Dictionary.Domain.Entities.Word", null)
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.Pronunciation", b =>
                {
                    b.HasOne("Gvn.GvnAI.Dictionary.Domain.Entities.Word", null)
                        .WithMany("Pronunciations")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.QuizAnswer", b =>
                {
                    b.HasOne("Gvn.GvnAI.Dictionary.Domain.Entities.QuizSession", null)
                        .WithMany("Answers")
                        .HasForeignKey("QuizSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gvn.GvnAI.Dictionary.Domain.Entities.Word", null)
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.QuizSession", b =>
                {
                    b.HasOne("Gvn.GvnAI.Dictionary.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.Sense", b =>
                {
                    b.HasOne("Gvn.GvnAI.Dictionary.Domain.Entities.SubjectDomain", null)
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Gvn.GvnAI.Dictionary.Domain.Entities.Register", null)
                        .WithMany()
                        .HasForeignKey("RegisterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Gvn.GvnAI.Dictionary.Domain.Entities.Word", null)
                        .WithMany("Senses")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.SenseAntonym", b =>
                {
                    b.HasOne("Gvn.GvnAI.Dictionary.Domain.Entities.Sense", null)
                        .WithMany()
                        .HasForeignKey("SenseId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gvn.GvnAI.Dictionary.Domain.Entities.Sense", null)
                        .WithMany()
                        .HasForeignKey("SenseId2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.SenseSynonym", b =>
                {
                    b.HasOne("Gvn.GvnAI.Dictionary.Domain.Entities.Sense", null)
                        .WithMany()
                        .HasForeignKey("SenseId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gvn.GvnAI.Dictionary.Domain.Entities.Sense", null)
                        .WithMany()
                        .HasForeignKey("SenseId2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.Translation", b =>
                {
                    b.HasOne("Gvn.GvnAI.Dictionary.Domain.Entities.PartOfSpeech", null)
                        .WithMany()
                        .HasForeignKey("PartOfSpeechId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Gvn.GvnAI.Dictionary.Domain.Entities.Register", null)
                        .WithMany()
                        .HasForeignKey("RegisterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Gvn.GvnAI.Dictionary.Domain.Entities.Sense", null)
                        .WithMany("Translations")
                        .HasForeignKey("SenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gvn.GvnAI.Dictionary.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("TargetLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.Word", b =>
                {
                    b.HasOne("Gvn.GvnAI.Dictionary.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gvn.GvnAI.Dictionary.Domain.Entities.PartOfSpeech", null)
                        .WithMany()
                        .HasForeignKey("PartOfSpeechId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gvn.GvnAI.Dictionary.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.WordRelationship", b =>
                {
                    b.HasOne("Gvn.GvnAI.Dictionary.Domain.Entities.Word", null)
                        .WithMany()
                        .HasForeignKey("SourceWordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gvn.GvnAI.Dictionary.Domain.Entities.Word", null)
                        .WithMany()
                        .HasForeignKey("TargetWordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.QuizSession", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.Sense", b =>
                {
                    b.Navigation("Examples");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Gvn.GvnAI.Dictionary.Domain.Entities.Word", b =>
                {
                    b.Navigation("Etymologies");

                    b.Navigation("Pronunciations");

                    b.Navigation("Senses");
                });
#pragma warning restore 612, 618
        }
    }
}
